// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1x-iOHLFFIFIpEWXtddlKiIal4arT9h8',
    appId: '1:43535381119:web:8642b7cf30e723a750854a',
    messagingSenderId: '43535381119',
    projectId: 'lonewolfbet',
    authDomain: 'lonewolfbet.firebaseapp.com',
    databaseURL: 'https://lonewolfbet-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lonewolfbet.firebasestorage.app',
    measurementId: 'G-M7VYF00TTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXR_6gD1_ljUyjiHJ6bRnwBa5LWP-bm4c',
    appId: '1:43535381119:android:78bc1def2430787e50854a',
    messagingSenderId: '43535381119',
    projectId: 'lonewolfbet',
    databaseURL: 'https://lonewolfbet-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lonewolfbet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIFdwOlRigCoMGsAAx48DixlP8LSFKUXA',
    appId: '1:43535381119:ios:3af181c23300c49250854a',
    messagingSenderId: '43535381119',
    projectId: 'lonewolfbet',
    databaseURL: 'https://lonewolfbet-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lonewolfbet.firebasestorage.app',
    iosBundleId: 'com.example.lonewolfcastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIFdwOlRigCoMGsAAx48DixlP8LSFKUXA',
    appId: '1:43535381119:ios:3af181c23300c49250854a',
    messagingSenderId: '43535381119',
    projectId: 'lonewolfbet',
    databaseURL: 'https://lonewolfbet-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lonewolfbet.firebasestorage.app',
    iosBundleId: 'com.example.lonewolfcastApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1x-iOHLFFIFIpEWXtddlKiIal4arT9h8',
    appId: '1:43535381119:web:0c09af58568fd7f850854a',
    messagingSenderId: '43535381119',
    projectId: 'lonewolfbet',
    authDomain: 'lonewolfbet.firebaseapp.com',
    databaseURL: 'https://lonewolfbet-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lonewolfbet.firebasestorage.app',
    measurementId: 'G-E1PVTZ57DQ',
  );
}
